name: Workflow Dispatch
on: workflow_dispatch
jobs:
  manual-trigger:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Trigger workflow from Github
        run: echo "Running on ${{ runner.os }}"
